/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BrokerCustomer;

import Business.EcoSystem;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shardul Negi
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private LabOrganization labOrganization;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.labOrganization = (LabOrganization)organization;
        
        populateTable();
    }
    
    public void populateTable(){
//        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
//        
//        model.setRowCount(0);
//        
//        for(WorkRequest request : labOrganization.getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[4];
//            row[0] = request;
//            row[1] = request.getSender().getEmployee().getName();
//            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
//            row[3] = request.getStatus();
//            
//            model.addRow(row);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustomerLogin = new javax.swing.JButton();
        brokerBtn = new javax.swing.JButton();
        brokerApprovalBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Customer-Broker Login Navigation Pane");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        CustomerLogin.setText("Customer Login");
        CustomerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerLoginActionPerformed(evt);
            }
        });
        add(CustomerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, -1));

        brokerBtn.setText("Broker Login");
        brokerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokerBtnActionPerformed(evt);
            }
        });
        add(brokerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 180, -1));

        brokerApprovalBtn.setText("Broker New Customer Approval");
        brokerApprovalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokerApprovalBtnActionPerformed(evt);
            }
        });
        add(brokerApprovalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    // navigate 
    private void CustomerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerLoginActionPerformed
        // TODO add your handling code here:
        
        if(this.userAccount.getUsername().contains("cust")|| this.userAccount.getUsername().contains("investor")){ 
        
        CustomerWorkBenchJPanel processWorkRequestJPanel = new CustomerWorkBenchJPanel(userProcessContainer ,userAccount, labOrganization, business );
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
                    JOptionPane.showMessageDialog(null,"Please log in to Broker Account/You are "
                            + "not authorized to enter in Customers account ");

        }
        
    }//GEN-LAST:event_CustomerLoginActionPerformed

    private void brokerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokerBtnActionPerformed
        // TODO add your handling code here:
               if(this.userAccount.getUsername().contains("bro") || this.userAccount.getUsername().contains("investor")){ 

        BrokerWorkBenchJPanel processWorkRequestJPanel = new BrokerWorkBenchJPanel(userProcessContainer ,userAccount, labOrganization, business );
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               }
               else{
                    JOptionPane.showMessageDialog(null,"Please log in to Customer Account/You are "
                            + "not authorized to enter in Broker's account ");
               }
    }//GEN-LAST:event_brokerBtnActionPerformed

    private void brokerApprovalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokerApprovalBtnActionPerformed
        // TODO add your handling code here:
        if(this.userAccount.getUsername().contains("bro") || this.userAccount.getUsername().contains("invest")){
        BrokerNewCustomerApprovalJPanel processWorkRequestJPanel = new BrokerNewCustomerApprovalJPanel(userProcessContainer ,userAccount, labOrganization, business );
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        else{
                 JOptionPane.showMessageDialog(null,"Please log in to Customer's Account/You are "
                            + "not authorized to enter in Broker's account ");
                }
    }//GEN-LAST:event_brokerApprovalBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerLogin;
    private javax.swing.JButton brokerApprovalBtn;
    private javax.swing.JButton brokerBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
